### ISSUE TITLE
Database error:::genre.validate

### ISSUE THREAD

**Issue by martinmurjas** [martinmurjas/acme-shopping#16]
Error when running the application: 

`/Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/sequelize/lib/model.js:726
        throw new Error(`Unrecognized datatype for attribute "${this.name}.${name}"`);
        ^

Error: Unrecognized datatype for attribute "genre.validate"
    at /Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/sequelize/lib/model.js:726:15
    at /Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/lodash/lodash.js:13469:38
    at /Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (/Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/lodash/lodash.js:13468:7)
    at genre.init (/Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/sequelize/lib/model.js:723:28)
    at Sequelize.define (/Users/jackfrost/Documents/FullStack Academy/acme-shopping/node_modules/sequelize/lib/sequelize.js:221:11)
    at Object.<anonymous> (/Users/jackfrost/Documents/FullStack Academy/acme-shopping/db/Genre.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)`

**Comment by martinmurjas** [comment]
Orzu fixed the error by updating the Genre and Category models
